### ISSUE TITLE
atom-alignment

### ISSUE THREAD

**Issue by tschf** [OraOpenSource/oracle-and-atom#5]
One of the comments in Tim's [blog](http://wphilltech.com/sublime-text-for-oracle-apex-developers/) for sublime plugins was `Abacus`. Which adds some alignment to fields.

e.g. converts this

``` plsql
foo.bar(
    p_param1 => 'p1',
    p_long_param_name => 'p2',
    p_sh => true
);
```

to

``` plsql
foo.bar(
    p_param1            => 'p1',
    p_long_param_name   => 'p2',
    p_sh                => true
);
```

Equivalent in Atom is `atom-alignment`

**Comment by martindsouza** [comment]
I'm not a fan of this style and do realize that others are. If you do implement this could it be optional?

**Comment by tschf** [comment]
At the end of the days, these are just suggested packages?
I added some detail in the PR branch to hopefully get across that it's just an optional? Would you like me to add some extra detail to signify more explicitly that it's optional?

**Comment by martindsouza** [comment]
You're right. I was getting this project confused with another Oracle atom project (the language pack)
